### PR TITLE
feat(parallel-tests): update Makefile to perform tests in parallel

### PR DESCRIPTION
**Pull request by glevco**
I noticed that running our tests take a long time, usually more than 1 hour in our CI though GitHub Actions. I tried this simple pytest plugin, [pytest-xdist](https://pypi.org/project/pytest-xdist/), which parallelizes test runs in multiple CPU cores. It's the main recommended plugin for that purpose, and has more than 1.1k starts on [GitHub](https://github.com/pytest-dev/pytest-xdist).

It's hard to get exact statistics on job execution times for a precise benchmark, but from taking a look at previous PRs and comparing with runs on [#532](https://github.com/HathorNetwork/hathor-core/actions/runs/4237710774/usage), the difference is noticeable. When running locally, on computers with more cores than the GitHub Actions runners, the time gains are even larger.

Acceptance criteria:

- Install the `pytest-xdist` plugin
- Update Makefile commands to parallelize tests

### CODE REVIEW

**Review by msbrogli — COMMENTED** [review]
What was the performance gain in your computer?

**Comment by jansegre** [comment]
I just noticed that the codecov wasn't updated (it needs the pytest plugin to run correctly). Maybe it's a one off error, can you check that it wasn't affected and that the codecov still updates correctly?

**Comment by glevco** [comment]
> What was the performance gain in your computer?

@msbrogli I ran `make tests-lib` on my computer (a Quad-Core Intel Core i7 MacBook Pro). In the `dev` branch, it takes 55minutes:

Screenshot 2023-02-24 at 15 31 52

In this branch, it takes 18 minutes:

Screenshot 2023-02-24 at 16 16 14

**Comment by glevco** [comment]
> I just noticed that the codecov wasn't updated (it needs the pytest plugin to run correctly). Maybe it's a one off error, can you check that it wasn't affected and that the codecov still updates correctly?

@jansegre it was probably a one off, it has been updated now

**Review by msbrogli — APPROVED** [review]

**Comment by msbrogli** [comment]
> > What was the performance gain in your computer?
> 
> @msbrogli I ran `make tests-lib` on my computer (a Quad-Core Intel Core i7 MacBook Pro). In the `dev` branch, it takes 55minutes:
> 
> In this branch, it takes 18 minutes:

Thanks for the benchmark.

**Pull request merged**
